# Generated by Django 4.2.2 on 2023-06-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filters',
            name='severity',
            field=models.CharField(choices=[('ALL', 'ALL'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default='LOW', max_length=20),
        ),
    ]
